MAIN_MENU = 0
WAIT_FOR_CSV = 1
AI_CHAT = 2
VOLUNTEER_HOME = 3
GUEST_HOME = 4
PROFILE_MENU = 5

WAIT_FOR_PROFILE_UPDATE = 6
REGISTRATION_TAG_SELECTION = 7
PROFILE_TAG_SELECTION = 8

WAIT_FOR_EVENTS_CSV = 10
REGISTRATION_CITY_SELECTION = 11
PROFILE_CITY_SELECTION = 12
EVENT_DETAILS = 13

MODERATION_MENU = 14
MODERATOR_EVENT_NAME = 15
MODERATOR_EVENT_DATE = 16
MODERATOR_EVENT_TIME = 17
MODERATOR_EVENT_CITY = 18
MODERATOR_EVENT_DESCRIPTION = 19
MODERATOR_EVENT_CONFIRMATION = 20
MODERATOR_SEARCH_REGISTERED_USERS = 22 # XD
MODERATOR_EVENT_CODE = 23
WAIT_FOR_EMPLOYEE_NUMBER = 24

REDEEM_CODE = 21
