MAIN_MENU = 0
WAIT_FOR_CSV = 1
AI_CHAT = 2
VOLUNTEER_HOME = 3
GUEST_HOME = 4
PROFILE_MENU = 5

WAIT_FOR_PROFILE_UPDATE = 6
REGISTRATION_TAG_SELECTION = 7
PROFILE_TAG_SELECTION = 8

REGISTRATION_CITY_SELECTION = 11
PROFILE_CITY_SELECTION = 12
EVENT_DETAILS = 13

ADMIN_MENU = 14
WAIT_FOR_ADMIN_ID = 15
WAIT_FOR_MODERATOR_ID = 16
WAIT_FOR_DELETE_USER_ID = 17
WAIT_FOR_FIND_USER_ID = 18
WAIT_FOR_FIND_USER_NAME = 19
WAIT_FOR_EVENTS_CSV = 20

MODERATION_MENU = 21
MODERATOR_EVENT_NAME = 22
MODERATOR_EVENT_DATE = 23
MODERATOR_EVENT_TIME = 24
MODERATOR_EVENT_CITY = 25
MODERATOR_EVENT_CREATOR = 26
MODERATOR_EVENT_DESCRIPTION = 27
MODERATOR_EVENT_PARTICIPATION_POINTS = 28
MODERATOR_EVENT_TAGS = 29
MODERATOR_EVENT_CODE = 30
MODERATOR_EVENT_CONFIRMATION = 31
MODERATOR_SEARCH_REGISTERED_USERS = 32 # XD
WAIT_FOR_EMPLOYEE_NUMBER = 33

REDEEM_CODE = 34
